In [1]:
import pandas as pd
import numpy as np
import os
import sys
notebook_dir = os.path.abspath(os.path.dirname(''))
project_root = os.path.dirname(notebook_dir)
sys.path.append(project_root)
import pandas as pd
from src.utils.db_utils import get_connection, execute_query
from src.features import team_level_features_class

ImportError: cannot import name 'team_level_features_class' from 'src.features' (c:\nfl predictive model\model\nfl_model\src\features\__init__.py)

In [ ]:
data=team_level_features_class.TeamLevelFeatures()

Successfully connected to the database!
creating efficiency stats

100%|██████████| 5/5 [00:00<00:00, 167.12it/s]

building team stats

100%|██████████| 20/20 [00:57<00:00,  2.86s/it]

In [ ]:
def_total_yards=data.team_stats_dict['defensive total_yards']
def_total_yards_normalized=data.stat_template.copy()
for i_team in def_total_yards.columns:
    def_total_yards_normalized[i_team]=(def_total_yards[i_team]-np.mean(def_total_yards, axis=1))/np.std(def_total_yards, axis=1)


def_total_yards_normalized

,ARI,ATL,BAL,BUF,CAR,CHI,CIN,CLE,DAL,DEN,...,NWE,NYG,NYJ,PHI,PIT,SEA,SFO,TAM,TEN,WAS
2022_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2022_2,1.845454,0.475187,0.408669,-1.413919,0.076080,-0.243206,-1.094634,-1.174455,-0.030349,-1.280884,...,-0.562491,0.129294,-1.001509,0.488490,1.100454,1.113758,-1.932758,-1.400616,0.594919,0.448580
2022_3,1.041196,0.304609,1.982390,-2.085205,-0.530189,0.492848,-0.661138,-0.178264,-0.685690,-1.618700,...,-1.103089,-0.415609,-0.047315,-0.284660,1.008459,0.992090,-2.167048,-1.086721,1.008459,1.008459
2022_4,0.699477,0.645986,2.024881,-2.325771,0.075408,0.241827,-0.602152,-0.370355,-0.572435,-1.660098,...,-0.530830,-0.049405,-0.144502,-0.851780,0.895613,0.943161,-2.093974,-0.988481,1.014484,1.038258
2022_5,-0.037536,0.826092,1.595415,-2.186677,0.026988,0.141146,-0.340301,-0.370082,-0.717518,-1.189039,...,0.041878,-0.245997,-0.360155,-1.337940,0.761568,1.654975,-2.186677,-0.469349,0.945213,0.538216
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024_17,0.209195,-0.059334,0.046450,0.442463,1.996678,0.914424,0.938835,0.125110,0.925273,-0.702177,...,0.241744,0.255306,-1.087340,-2.242830,-0.547569,0.057300,-1.326033,0.708280,-1.168713,-0.569269
2024_18,-0.025952,0.118928,-0.300190,0.258634,2.439601,0.667404,0.856266,-0.046650,0.964926,-0.269144,...,0.447496,0.507001,-1.027179,-2.336277,-0.406263,-0.372630,-1.019418,0.312964,-1.241913,-0.561492
2024_19,0.210205,0.319167,-0.545262,0.169042,2.762329,0.692058,0.447499,0.193256,0.733221,-0.835827,...,0.224733,0.386965,-0.973845,-2.431509,-0.441143,-0.194164,-0.823720,0.178727,-1.077964,-0.431458
2024_20,0.211426,0.321658,-0.655049,-0.102122,2.793298,0.698895,0.451487,0.194279,0.740539,-0.490791,...,0.226124,0.390247,-0.986425,-2.406373,-0.129884,-0.197656,-0.834550,0.198634,-1.091758,-0.537061
2024_21,0.184948,0.296359,-0.798725,0.047476,2.794439,0.677632,0.427576,0.167618,0.719720,-0.524780,...,0.199803,0.365681,-1.025717,-2.189863,-0.160013,-0.228510,-0.872217,0.172019,-1.132176,-0.136384

In [ ]:
def_total_yards["ARI"]

2022_1            NaN
2022_2     488.000000
2022_3     406.000000
2022_4     383.666667
2022_5     342.750000
              ...
2024_17    342.000000
2024_18    336.687500
2024_19    342.529412
2024_20    342.529412
2024_21    342.529412
Name: ARI, Length: 65, dtype: float64

In [ ]:
data.single_stats_dict['normalized team points'].fillna(0).rolling(window=5).mean()

,ARI,ATL,BAL,BUF,CAR,CHI,CIN,CLE,DAL,DEN,...,NYJ,OAK,PHI,PIT,SDG,SEA,SFO,TAM,TEN,WAS
2016_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_5,1.041636,0.995762,1.475060,1.235041,0.899201,0.565091,0.605866,0.549001,1.089281,1.114211,...,0.573778,0.732519,1.657778,1.038409,0.926619,1.276785,0.436423,0.406167,0.724241,0.615974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024_15,0.696322,0.445540,0.811290,1.586366,0.521750,0.938556,0.946350,0.738948,0.842495,1.609586,...,0.953415,0.000000,1.511620,1.408218,0.000000,0.922909,0.685993,0.998684,0.733621,0.940864
2024_16,0.970832,0.673055,0.971555,1.492259,0.762898,0.888311,0.913886,0.667829,0.964575,1.486280,...,0.778617,0.000000,1.595025,1.365923,0.000000,0.974709,0.683257,1.204819,0.857756,1.094966
2024_17,0.995233,0.879359,0.994488,1.854797,0.682454,0.625856,1.142894,0.497965,0.784474,1.393874,...,0.900710,0.000000,1.616247,1.231690,0.000000,0.893197,0.885431,1.388346,0.707936,1.118195
2024_18,1.213811,1.095824,1.158474,1.643389,0.817502,0.643781,1.006265,0.314294,0.734896,1.297742,...,0.976467,0.000000,1.571610,0.877113,0.000000,0.938654,0.998245,1.414888,0.666315,0.952146
2024_19,1.047015,0.922628,1.422186,1.479802,0.712584,0.513781,0.815677,0.205204,0.593303,1.374269,...,0.743631,0.000000,1.576272,0.725003,0.000000,0.666956,0.689092,1.364484,0.622941,1.152146

In [ ]:
data.team_stats_dict.keys()

dict_keys(['defensive turnovers', 'offensive turnovers', 'defensive total_yards', 'offensive total_yards', 'defensive first_downs', 'offensive first_downs', 'defensive passing tds', 'offensive passing tds', 'defensive interceptions', 'offensive interceptions', 'defensive rush attempts', 'offensive rush attempts', 'defensive rush yards', 'offensive rush yards', 'defensive rush tds', 'offensive rush tds', 'defensive fumbles', 'offensive fumbles', 'defensive fumbles lost', 'offensive fumbles lost', 'defensive sacks', 'offensive sacks', 'defensive sacked yards', 'offensive sacked yards', 'defensive penalties', 'offensive penalties', 'defensive penalty yards', 'offensive penalty yards', 'defensive completion efficiency', 'offensive completion efficiency', 'defensive average completion', 'offensive average completion', 'defensive fourth down efficiency', 'offensive fourth down efficiency', 'defensive rushing efficiency', 'offensive rushing efficiency', 'defensive third down efficiency', 'offensive third down efficiency', 'defensive team points', 'offensive team points', 'normalize turnovers 2 ', 'normalize turnovers 5 ', 'normalize turnovers 10 ', 'normalize total_yards 2 ', 'normalize total_yards 5 ', 'normalize total_yards 10 ', 'normalize first_downs 2 ', 'normalize first_downs 5 ', 'normalize first_downs 10 ', 'normalize passing tds 2 ', 'normalize passing tds 5 ', 'normalize passing tds 10 ', 'normalize interceptions 2 ', 'normalize interceptions 5 ', 'normalize interceptions 10 ', 'normalize rush attempts 2 ', 'normalize rush attempts 5 ', 'normalize rush attempts 10 ', 'normalize rush yards 2 ', 'normalize rush yards 5 ', 'normalize rush yards 10 ', 'normalize rush tds 2 ', 'normalize rush tds 5 ', 'normalize rush tds 10 ', 'normalize fumbles 2 ', 'normalize fumbles 5 ', 'normalize fumbles 10 ', 'normalize fumbles lost 2 ', 'normalize fumbles lost 5 ', 'normalize fumbles lost 10 ', 'normalize sacks 2 ', 'normalize sacks 5 ', 'normalize sacks 10 ', 'normalize sacked yards 2 ', 'normalize sacked yards 5 ', 'normalize sacked yards 10 ', 'normalize penalties 2 ', 'normalize penalties 5 ', 'normalize penalties 10 ', 'normalize penalty yards 2 ', 'normalize penalty yards 5 ', 'normalize penalty yards 10 ', 'normalize completion efficiency 2 ', 'normalize completion efficiency 5 ', 'normalize completion efficiency 10 ', 'normalize average completion 2 ', 'normalize average completion 5 ', 'normalize average completion 10 ', 'normalize fourth down efficiency 2 ', 'normalize fourth down efficiency 5 ', 'normalize fourth down efficiency 10 ', 'normalize rushing efficiency 2 ', 'normalize rushing efficiency 5 ', 'normalize rushing efficiency 10 ', 'normalize third down efficiency 2 ', 'normalize third down efficiency 5 ', 'normalize third down efficiency 10 ', 'normalize team points 2 ', 'normalize team points 5 ', 'normalize team points 10 '])

In [ ]:
data.team_stats_dict["offensive team points"]

,ARI,ATL,BAL,BUF,CAR,CHI,CIN,CLE,DAL,DEN,...,NYJ,OAK,PHI,PIT,SDG,SEA,SFO,TAM,TEN,WAS
2016_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_2,21.000000,24.000000,13.000000,7.000000,20.000000,14.000000,23.000000,10.000000,19.000000,21.000000,...,22.000000,35.000000,29.000000,38.000000,27.000,12.000000,28.000000,31.000000,16.000000,16.000000
2016_3,30.500000,29.500000,19.000000,19.000000,33.000000,14.000000,19.500000,15.000000,23.000000,27.500000,...,29.500000,31.500000,29.000000,31.000000,32.500,7.500000,27.500000,19.000000,16.000000,19.500000
2016_4,26.333333,34.666667,19.000000,23.666667,25.333333,15.000000,18.666667,18.000000,25.666667,28.000000,...,20.666667,26.666667,30.666667,21.666667,29.000,17.333333,24.333333,23.333333,14.000000,22.666667
2016_5,23.000000,38.000000,21.000000,21.750000,27.250000,15.500000,19.500000,18.500000,25.250000,27.750000,...,19.750000,27.000000,30.666667,27.000000,30.250,19.750000,22.500000,19.250000,15.500000,24.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024_15,21.846154,21.384615,29.461538,30.538462,17.923077,19.538462,27.846154,17.846154,20.615385,23.461538,...,19.307692,19.562500,26.307692,24.846154,25.625,23.230769,23.692308,27.923077,17.461538,28.923077
2024_16,22.428571,20.928571,29.857143,31.785714,17.642857,19.000000,28.500000,17.071429,21.285714,24.000000,...,20.214286,19.562500,26.357143,24.000000,25.625,22.500000,22.428571,28.785714,18.142857,28.285714
2024_17,22.933333,21.800000,30.133333,31.266667,18.866667,18.866667,28.200000,16.333333,21.600000,24.200000,...,19.466667,19.562500,26.800000,23.533333,25.625,22.600000,22.066667,28.466667,18.933333,28.800000
2024_18,22.062500,21.937500,30.187500,31.812500,18.562500,17.875000,28.312500,15.500000,20.687500,24.187500,...,19.125000,19.562500,27.687500,22.687500,25.625,21.562500,22.812500,29.687500,18.562500,28.875000
2024_19,23.529412,22.882353,30.470588,30.882353,20.058824,18.235294,27.764706,15.176471,20.588235,25.000000,...,19.882353,19.562500,27.235294,22.352941,25.625,22.058824,22.882353,29.529412,18.294118,28.529412

In [ ]:
data.single_stats_dict["turnovers"].index.str.split('_', expand=True)[0][0]

'2016'

In [ ]:
data.stat_template

,ARI,ATL,BAL,BUF,CAR,CHI,CIN,CLE,DAL,DEN,...,NYJ,OAK,PHI,PIT,SDG,SEA,SFO,TAM,TEN,WAS
2016_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2016_5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2024_15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024_16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024_17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024_18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2024_19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ari_index=np.where(data.data['teamid']=='ARI')[0]
ari_index

array([  27,   51,   66,  117,  126,  183,  211,  218,  287,  308,  328,
        375,  398,  439,  470,  502,  544,  568,  627,  649,  674,  705,
        732,  790,  799,  834,  877,  909,  937,  970, 1007, 1042, 1091,
       1120, 1157, 1183, 1218, 1236, 1255, 1303, 1346, 1381, 1410, 1428,
       1475, 1490, 1539, 1574, 1623, 1652, 1685, 1717, 1732, 1775, 1800,
       1828, 1845, 1886, 1916, 1977, 2009, 2037, 2076, 2108, 2160, 2191,
       2223, 2234, 2270, 2316, 2343, 2395, 2415, 2430, 2474, 2505, 2532,
       2575, 2589, 2642, 2690, 2725, 2744, 2788, 2825, 2850, 2879, 2887,
       2938, 2961, 2996, 3036, 3087, 3094, 3125, 3174, 3211, 3226, 3263,
       3298, 3329, 3360, 3395, 3422, 3431, 3468, 3507, 3536, 3569, 3591,
       3657, 3678, 3719, 3724, 3778, 3826, 3861, 3897, 3932, 3955, 3988,
       4012, 4045, 4060, 4099, 4120, 4159, 4182, 4249, 4278, 4306, 4339,
       4386, 4435, 4465, 4495, 4526, 4540, 4593, 4606, 4645, 4677, 4732,
       4752, 4787, 4813, 4836, 4870, 4913], dtype=int64)

In [ ]:
season_loc=data.data.columns.get_loc('season')
week_loc=data.data.columns.get_loc('week')
defenseid_loc=data.data.columns.get_loc('defenseid')
ari_master_index=data.data.iloc[ari_index, season_loc].astype(str)+'_'+data.data.iloc[ari_index, week_loc].astype(str)

In [ ]:
ari_defense=data.data.iloc[ari_index, defenseid_loc]
ari_defense

3118    NWE
3142    TAM
3157    BUF
3208    LAR
3217    SFO
       ...
4786    SEA
4812    NWE
4836    CAR
4870    LAR
4913    SFO
Name: defenseid, Length: 149, dtype: object

In [ ]:
data.stat_template.loc[ari_master_index, 'ARI']=ari_defense.values

In [ ]:
data.stat_template.loc[ari_master_index, 'ARI']

2016_1     NWE
2016_2     TAM
2016_3     BUF
2016_4     LAR
2016_5     SFO
          ...
2024_14    SEA
2024_15    NWE
2024_16    CAR
2024_17    LAR
2024_18    SFO
Name: ARI, Length: 149, dtype: object

In [ ]:
from src import config

features=config.team_feature_configs.team_features